Develop
usermindinc/UberStream pull request #5
Opened 2022-06-22 22:16 UTC by gcoffmanQ

2022-06-22 22:37 UTC, cfluture commented on UberStream_Log_Cleanup.py
> +processingTimestamp < '[CUTOFF_TIMESTAMP]';
have to use processingDate in order to take advantage of partitioning, precision is not important as we are cleaning logs

2022-06-22 22:37 UTC, cfluture commented on Über Stream.scala
>    val df = spark.sql(f"SELECT * FROM streaming_logs.$table%s")
potentially expensive, use DESCRIBE TABLE instead, this will only call the meta store no matter how big the table is

2022-06-23 00:14 UTC, gcoffmanQ commented on Über Stream.scala
>    val df = spark.sql(f"SELECT * FROM streaming_logs.$table%s")
Databricks SQL didn't have DESCRIBE TABLE so I used their function SHOW COLUMNS and then performed a where on that to find the dateColumn

2022-06-23 17:14 UTC, cfluture requested changes

2022-06-23 17:14 UTC, cfluture commented on Über Stream.scala
> +    val df = spark.sql(f"SELECT * FROM streaming_logs.$table%s")
there is no need to read as a dataframe, use CREATE TABLE AS SELECT query instead

2022-06-23 17:14 UTC, cfluture commented on Über Stream.scala
> -      .withColumn(columnNameToCheck, to_date(col("processingTimestamp"),"yyyy-MM-dd"))
use CREATE TABLE AS SELECT query instead

2022-06-27 19:19 UTC, cfluture approved these changes

2022-07-08 21:39 UTC, closed without merging